version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: cloud-compiler-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models:/root/.ollama/models
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
