services:
  # Backend API Service
  - type: web
    name: ai-code-compiler-backend
    runtime: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: AI_PROVIDER
        value: openai
      - key: OPENAI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        fromGroup: web
      - key: DEBUG
        value: False
      - key: ALLOWED_ORIGINS
        fromService:
          type: web
          name: ai-code-compiler-frontend
          property: url
      - key: SECRET_KEY
        generateValue: true
    healthCheckPath: /api/ping

  # Frontend Static Site
  - type: web
    name: ai-code-compiler-frontend
    runtime: static
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: VITE_API_BASE
        fromService:
          type: web
          name: ai-code-compiler-backend
          property: url
      - key: VITE_APP_NAME
        value: Cloud Code Compiler
      - key: VITE_APP_VERSION
        value: 1.0.0
    headers:
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
